language: node_js
node_js:
  - 16

services:
  - docker

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed/.
  - docker tag udagram-api-user freeleons/udagram-api-feed:latest

  - docker --version # print the version for logging
  - docker build -t udagram-api-user ./udagram-api-user/.
  - docker tag udagram-api-user freeleons/udagram-api-user:latest

  - docker --version # print the version for logging
  - docker build -t udagram-frontend ./udagram-frontend/.
  - docker tag udagram-frontend freeleons/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push -a
