apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: freeleons/udagram-api-feed:latest
        ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-secret
        - secretRef:
            name: aws-secret
