apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    app: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      restartPolicy: Always
      containers:
        - name: udagram-api-frontend
          image: freeleons/udagram-api-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          volumeMounts:
            - name: aws-secret
              mountPath: "/root/.aws/"
              readOnly: true
          env:
            env:
              - name: POSTGRES_DB
                valueFrom:
                  configMapKeyRef:
                    name: env-configmap
                    key: POSTGRES_DB
              - name: POSTGRES_HOST
                valueFrom:
                  configMapKeyRef:
                    name: env-configmap
                    key: POSTGRES_HOST
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: env-secret
                    key: POSTGRES_PASSWORD
              - name: POSTGRES_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: env-secret
                    key: POSTGRES_USERNAME
              - name: AWS_BUCKET
                valueFrom:
                  configMapKeyRef:
                    name: env-configmap
                    key: AWS_BUCKET
              - name: AWS_REGION
                valueFrom:
                  configMapKeyRef:
                    name: env-configmap
                    key: AWS_REGION
              - name: AWS_PROFILE
                valueFrom:
                  configMapKeyRef:
                    name: env-configmap
                    key: AWS_PROFILE
              - name: JWT_SECRET
                valueFrom:
                  configMapKeyRef:
                    name: env-configmap
                    key: JWT_SECRET
              - name: URL
                valueFrom:
                  configMapKeyRef:
                    name: env-configmap
                    key: URL
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
