language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

before_script:
  - docker --version # print the version for logging
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend freeleons/udagram-frontend:latest

script: 'true'
# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push freeleons/udagram-frontend
