apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-frontend
  name: udagram-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: udagram-frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
